### ISSUE TITLE
Error messages encountered while dealing with the poker questionsl

### ISSUE THREAD

**Issue by xRayWx** [alain-picard/clojure-training#11]
Hello,

While working on the poker hand problems, I am constantly encountering the following errors and I am not quite sure what the truely meant:
````
Don't know how to create ISeq from: java.lang.Character
````
````
Java.lang.Chracter cannot be cast to clojure.lang.IFn
````

**Comment by alain-picard** [comment]
This error is very common:
  Foo cannot be cast to clojure.lang.IFn
In english, this means, you're trying to use a foo as a function.  So you probably have
code which (unintentionally) tries to do:
(\h "args")
with the charcter \h in the "function" position.

Does that help?

**Comment by raywai-apek** [comment]
Yeah thanks, I think I get it now, and saw how that came about from my code. 

What about this one?
`Don't know how to create ISeq from: java.lang.Character`

**Comment by alain-picard** [comment]
Almost the same:  
It says you're trying to use a character as a sequence.  As if you code has:

(take 3 \h)
or (first \h)
or some other function which expects to operate on a seq, but for which a char was given instead.
