### ISSUE TITLE
Finding straight in a hand using partition

### ISSUE THREAD

**Issue by xRayWx** [alain-picard/clojure-training#16]
Hello,

Last night I was trying to use the **partition** to try to look for the possible substring from another string, say "A123456", however, I can't really get that working, from the examples on https://clojuredocs.org/clojure.core/partition, it looks like it only work on numbers?

**Comment by alain-picard** [comment]
```
(partition 2 "A12345") ; => ((\A \1) (\2 \3) (\4 \5))

(partition 3 "A12345") ; => ((\A \1 \2) (\3 \4 \5))
```
Seems to work just fine.  Perhaps it doesn't do what you think it does?
Give me a sample input and expected output and I can help some more.

**Comment by xRayWx** [comment]
For example in the following code snippet:

````
(defn my-fun []
  (let [[suit rank] (apply map vector ["S4" "S3" "C5" "S2" "H6"])
        my-hand (partition 5 1 ["A" "2" "3" "4" "5" "6" "7" "8" "9" "T" "J" "Q" "K"])]
    (println my-hand) ;;((A 2 3 4 5) (2 3 4 5 6) (3 4 5 6 7) ...(9 T J Q K))
    (println (sort rank)) ;; (2 3 4 5 6)
    (println (.contains my-hand (lazy-seq (sort rank)))))) ;; false

(my-fun)
````

I do not understand why the .contains function returns false while my-hand clearly contains the sequence (2 3 4 5 6). I have also made sure they are both of the same class, which is lazy-seq, even though that should not make a difference.

**Comment by alain-picard** [comment]
Probably because ".contains" is a java function which doesn't do what you think, especially on lazy sequences.

For example:
`
(some #{[2 3 4]}  [[1 2 3] [2 3 4] [3 4 5]])
`
and
`
(some #{[1 2 3]} (partition 3 1 (range 5)))
`
both work as you expect.

**Comment by raywai-apek** [comment]
I realised using
(partition 5 1 [\A \2 \3 \4 \5 \6 \7 \8 "\9 "\T "\J \Q \K]
instead of 
(partition 5 1 ["A" "2" "3" "4" "5" "6" "7" "8" "9" "T" "J" "Q" "K"])

would work for the ".contains" java function.
