### ISSUE TITLE
problem with keystroke C-x C-e in Emacs

### ISSUE THREAD

**Issue by PatrickHo-134** [alain-picard/clojure-training#21]
Hi Alain,

I'm having a problem while using emacs for editing my code. I usually use keystroke C-x C-e to evaluate a form in Clojure, but somehow it stops working after a while. I'm not sure if I accidentally typed a key binding that terminates this function? It happened a few times in a row so I had to constantly restart my emacs. Can you help me with this? 

Thank you and best regards

**Comment by xRayWx** [comment]
Hey Patrick,

It is great to see another emac user here!

This has actually happened to me before as well, but for some other key strokes, what I did was to kill the current buffer and re-open it again, perhaps you could give it a try first?

Ray

**Comment by PatrickHo-134** [comment]
Yeah, that's why I had to restart emacs to make sure the problem solved :)

My guess is the application is running another endless operation that it can't evaluate the current code

**Comment by xRayWx** [comment]
Ah right, come to think of it, this happened to me when I was working on some loop structures that ended up in an infinite loop.

**Comment by alain-picard** [comment]
Sorry to be so late to the party!

Ray, I expect what's happening is you launched a function which takes a very
long time to execute (maybe even an infinite loop?)  

A symptom of this is when you can't type in the repl window.

You can often get yourself out of trouble with this command:

>  C-c C-b runs the command cider-interrupt (found in cider-mode-map),

I might try to discuss this tonight.
