### ISSUE TITLE
Is there a way to convert a regex to a string in clojure?

### ISSUE THREAD

**Issue by Yunfeng-Song** [alain-picard/clojure-training#29]
For example. convert #"aaa" to "aaa" ?
And the reason is that I may receive a regex as an input, but I need to modify it before I can pass it into functions.

**Comment by raywai-apek** [comment]
Hello Yunfeng,

Yes there is! You might want to check out [re-pattern](https://clojuredocs.org/clojure.core/re-pattern), #"" is just a reader macro for creating regex

Hope that helps,
Ray

**Comment by PatrickHo-134** [comment]
@raywai-apek I think re-pattern takes a string and turns it into a regex pattern?? (please correct me if I'm wrong :) )

**Comment by PatrickHo-134** [comment]
@Yunfeng-Song you can try (str #"aaa"). it will return an output "aaa" as a string

**Comment by xRayWx** [comment]
@PatrickHo-134 Ah you are right, I thought he is trying to read in a regex as an argument of a function

**Comment by Yunfeng-Song** [comment]
I didn't know it's easy like that haha. Thanks guys.
