### ISSUE TITLE
Can the Group-by function returns a set instead of a map?

### ISSUE THREAD

**Issue by xRayWx** [alain-picard/clojure-training#3]
According the the Clojuredoc https://clojuredocs.org/clojure.core/group-by
The group-by function returns a map, however, I want to turn it into a set in the same line, however, I have got no luck, am I missing something?

**Comment by alain-picard** [comment]
Yes.  Hello @xRayWx !

The docstring of group-by says:
Added in 1.2
  Returns a map of the elements of coll keyed by the result of
  f on each element. The value at each key will be a vector of the
  corresponding elements, in the order they appeared in coll.

If you want to turn a map into a set, you first need
to decide: what do you want to be into the set, the
keys, or the values?  If the values, the following would work:

```
(let [m {:foo "Hello" :bar "There"}]
  (into #{}
        (vals m)))  ; => #{"There" "Hello"}
```

I hope this helps!

**Comment by xRayWx** [comment]
Hello @alain-picard ,

Thanks for the feedback! Strangely enough, the (into #{} (vals m)) in my case would still return the inner elements in a list

```
(let [m (group-by frequencies words)]
  (into #{} (vals m)))   ; => #{("meat" "mate" "team") ("mat") ("eat")}
```

However, using map set works for me in this case.

``` 
(let [m (group-by frequencies words)]
  (map set (vals m)))   ; => (#{"meat" "mate" "team"} #{"mat"} #{"eat"}
```

I am a little confused since both seems to be doing the same thing? Anyway I have just made a pull request on the completed anagram assignment.

**Comment by alain-picard** [comment]
Ah! Yes, I think I misunderstood your question

Yes: (map set coll) does what you want, because
(set coll) => #{x1 x2 ...}
so you're just creating an set of each inner collection, so
(into #{} 
        (map set (vals m)))
will give you a set of inner sets.  Well done!
