### ISSUE TITLE
What's the preferred way of converting a string to a number in clojure?

### ISSUE THREAD

**Issue by Yunfeng-Song** [alain-picard/clojure-training#32]
I am using clojure.edn/read-string function at the moment because it is concise. But is there a better way of doing this?

eg: (clojure.edn/read-string "-0.1") => -0.1

**Comment by alain-picard** [comment]
If you know what type you'll want, you can use the Java function; e.g.

(Double/valueOf "0.3") ; => 0.3

but if you don't know what type to expect, what you did (read-string) is perfect.
