### ISSUE TITLE
Can we break a loop in clojure?

### ISSUE THREAD

**Issue by PatrickHo-134** [alain-picard/clojure-training#33]
Hi guys,

I have two pieces of code here:
```
(for [noun (range 10)]
  (for [verb (range 10)]
    (if (= 21 (+ (* 10 noun) verb))
      (println noun verb))))
```

```
(loop [noun 0]
  (when (< noun 10)
    (loop [verb 0]
      (when (< verb 10)
        (if (= 21 (+ (* 10 noun) verb))
          (println noun verb))
        (recur (+ verb 1))))
    (recur (+ noun 1))))
````

What I'm trying to do is print the result when it satisfies an if condition  in a nested loop. However, the first one prints out a sequence including results that I don't want. Is there a way to break the loop when it meets if statement?

The second one prints out the result I want (in REPL) only when I call recur at the end. Otherwise, it just returns nil.

Is there a better way to get an output here?

**Comment by privisi** [comment]
From what I've read, there is no way to break; or return; out of a loop in Clojure.
However a good way to implement something close to a break would be to keep the recur in the else part of an if statement, for example
```
(loop [x 100]
  (if (satisfies-some-condition? x)
    x
    (recur (do-something x))))
```

**Comment by alain-picard** [comment]
Reading your code, I'm not 100% sure what you're trying
to achieve, but if it does what I think it does, you're
almost always better off trying to compose functional
idioms to do this sort of thing.  _e.g._

```
(defn cross-product [n m]
  (for [i (range n)
        j (range m)]
    [i j]))

(filter (fn [[noun verb]]
          (= 21 (+ (* 10 noun) verb)))
        (cross-product 10 10))
```

If you're trying to "break out of the loop" early, to me
that sounds like a `(take 1 (...))` sort of idiom?

**Comment by PatrickHo-134** [comment]
I didn't approach the problem in the way of functional programming in the first place. So I generated a sequence of pair values just like what you did in the first function and it solved the problem all along. 

Thank you.
