### ISSUE TITLE
Chapter 7 Preparatory Material wrong port

### ISSUE THREAD

**Issue by privisi** [alain-picard/clojure-training#35]
The link `http://localhost:3000` might be a mistype.
I think it's because the request is using port 3001
```
(def server
  (run-jetty #'handler {:port 3001 :join false}))
```
When I use `http://localhost:3001` it works

**Comment by xRayWx** [comment]
Oh yeah, got mine running, thanks

**Comment by xRayWx** [comment]
By the way, anyone has any idea how to stop the server without restarting REPL?

**Comment by privisi** [comment]
I had to go into control panel and kill the java process running as the server

**Comment by alain-picard** [comment]
Yes -- sorry about that... my bad. :-(

And you can stop the server by running
(.stop server)
