### ISSUE TITLE
Where do we run the (.stop server) command

### ISSUE THREAD

**Issue by xRayWx** [alain-picard/clojure-training#38]
Trying out the new simply playground code, encountered the following exception
````
java.net.BindException: Address already in use
````
Had to to the following to kill the process on MacOS

````
sudo lsof -i :3001
````

````
kill -9 <PID>
````
Also, is anyone able to run the server? I was able to run the previous "hello world" server, but for this I keep getting "site can't be reached"

**Comment by alain-picard** [comment]
Only one process at a time can bind a port on unix, so you have to exit any previous repl before trying to start a new one.
