### ISSUE TITLE
Is this how we run the server?

### ISSUE THREAD

**Issue by xRayWx** [alain-picard/clojure-training#39]
Did the following in terminal
````
lein repl
````
However, port 3001 still cannot be reached, and does nREPL server started on port 50223 has anything to do with it?

<img width="425" alt="Screen Shot 2020-05-10 at 10 01 49 pm" src="https://user-images.githubusercontent.com/32470625/81498734-f9040380-9309-11ea-8cc7-e940ce57e68d.png">

Also, I realised we run (.stop server) in the terminal, is that right?

**Comment by alain-picard** [comment]
You should be able to visit http://localhost:3001 in your browser?  Also, you can just exit the repl with Ctrl-d (control d).

**Comment by PatrickHo-134** [comment]
I have the same issue.  cant reach port 3001

**Comment by alain-picard** [comment]
Does lein repl start cleanly, or are there error messages?  Anyway, don't worry about it, we'll do it during class.
