### ISSUE TITLE
[SOLUTION] Displaying page on browser instead of downloading

### ISSUE THREAD

**Issue by privisi** [alain-picard/clojure-training#41]
Hey guys,
Did a bit of research and turns out that the handlers need to add content type text/plain in order to be displayed on a web browser
For example:
```
(defn new-game-handler []
  (when (game/new-game!)
    (-> "OK- start guessing at /guess"
        (response)
        (content-type "text/plain"))))
```
make sure you include content-type in :require
` [ring.util.response :refer [response content-type ...]]`

**Comment by raywai-apek** [comment]
Wow! This is great, thanks for the help, I will give that a try tonight

**Comment by alain-picard** [comment]
Correct.  See also the email I sent out this morning, for a slightly deeper analysis.

Good job!

**Comment by Yunfeng-Song** [comment]
One possible way to implement this based on Benson's idea.
```
(defn content-type-middleware
  [handler]
  (fn [request]
    (-> request
        (handler)
        (content-type "text/plain"))))

(def handler
  (-> game-routes
      (middleware/wrap-defaults middleware/api-defaults)
      (content-type-middleware)))
```

**Comment by PatrickHo-134** [comment]
I tried both ways but it still didn't display in my browser :(

In the meantime, I am able to test the application with postman or curl. So not a big problem at the moment!

update: I solved it! Thank you very much

**Comment by xRayWx** [comment]
Patrick, did you get it working? The solution on Alain's email worked for me, try following the format of "/new-game/with-type" in "game-routes"?
