### ISSUE TITLE
what does test client mean in the assignment requirement?

### ISSUE THREAD

**Issue by Yunfeng-Song** [alain-picard/clojure-training#42]
In the login function, I don't fully understand what do you mean by 

> Modify your test client so that this authorization is sent; the server should refuse to play the game if the authorization is not present.

do you mind explaining more about it?

Right now, what I did for the login function is first adding a new atom called login?, using a login URL to set this atom to be true and before starting the game or guessing, check the login? first. Is it enough?

**Comment by xRayWx** [comment]
I think we should first check if we "know" the player, if we don't, then we do not start the game.
So I guess we should store some "players",  then we use this "authorization" function or middleware to first check if we "know" the player.

**Comment by alain-picard** [comment]
Is using curl, for example, you can send

- additional HTTP headers  (with -H)
- cookies (with -b)
- form data (with -X POST -d data)

Any of these (including specially constructed URIs) could be used to do the task.

Does that help?

**Comment by Yunfeng-Song** [comment]
Yeah, I think that makes sense because I am using cookies right now to support the login function and make multi-player function possible.
