### ISSUE TITLE
Access denied when pushing?!

### ISSUE THREAD

**Issue by xRayWx** [alain-picard/clojure-training#43]
<img width="715" alt="Screen Shot 2020-05-13 at 3 39 54 am" src="https://user-images.githubusercontent.com/32470625/81726959-95293880-94cb-11ea-970a-3e42fb2a044f.png">

I am sure I should have the same set up for the clojure-training repository, how come I am seeing access denial in here?

**Comment by alain-picard** [comment]
You can't push to my repo.  You can push to your own clone, or raise a PR.
