### ISSUE TITLE
Installing Localstack

### ISSUE THREAD

**Issue by xRayWx** [alain-picard/clojure-training#46]
I am using MacOS Catalina 10.15.4, I had a lot of trouble with Localstack. I was able to get Localstack installed, however, when I tried to run 
````
localstack start
````
and it returned command not found, I am guessing there is an issue with my path? I tried tweaking it, no luck, and I believe I have seriously messed up my paths in the process.

Anyway, tried running using docker with the following command in the repository folder:
````
TMPDIR=/private$TMPDIR docker-compose up
````
Then I am finally able to see the following in my localhost:4566 (by the way, seems like all other ports are now depreciated?)

<img width="279" alt="Screen Shot 2020-05-14 at 11 26 10 pm" src="https://user-images.githubusercontent.com/32470625/81941164-ccb6f280-963b-11ea-8f5e-72c0da2e213d.png">

Am I on the right track? But by using docker, does that mean I cannot build and test my code offline?

Update: Yes I am on the right track.

**Comment by alain-picard** [comment]
Glad you got that working!
