### ISSUE TITLE
Could not locate amazonica?

### ISSUE THREAD

**Issue by xRayWx** [alain-picard/clojure-training#48]
I have added the amazonica in my dependencies.
<img width="706" alt="Screen Shot 2020-05-15 at 10 41 36 pm" src="https://user-images.githubusercontent.com/32470625/82051494-4e228980-96fd-11ea-8fb4-41ff97d93e9b.png">
However, when I am including the library in my databse.clj like so:
<img width="419" alt="Screen Shot 2020-05-15 at 10 52 18 pm" src="https://user-images.githubusercontent.com/32470625/82052338-cfc6e700-96fe-11ea-87b4-0b306fad1ab8.png">
It is saying could not find amazonica in my class path?
<img width="557" alt="Screen Shot 2020-05-15 at 10 53 39 pm" src="https://user-images.githubusercontent.com/32470625/82052411-eff6a600-96fe-11ea-8b64-1952009dd024.png">

I am pretty sure the classpath is messed up, anyone knows how to fix that and where do I point it to?

EDIT: Okay, finally got my dynamoDB working and was able to create tables from Clojure, so I am now temporarily happy. The followings are a few of my pitfalls that I encountered, they may seem to be some easy catch so I would assume no one would be as silly as me, but I thought I might list them out just to remind myself or possibly help out someone who might find themselves in similar situations.

- Creating the REPL from the correct name space (The above problem)
 -- I first created a REPL from a clj file, then I proceeded to create another file for database (with another namespace), then I tried run the REPL from the second namespace, and REPL is complaining it cannot find amazonica in the class file. In short, I run REPL again on the new namespace and got it to recognise amazonica.

- Table needs provisioned throughput
 -- Got another error when I am trying to quickly testing out some tables, initially I omitted the provisioned-throughput. However, attribute-definitions, key-schema, and provisioned-throughput seem to be some keywords to defined that we cannot ignore.

**Comment by alain-picard** [comment]
Glad you got it working!
