### ISSUE TITLE
core.async problem-which one gets printed first?

### ISSUE THREAD

**Issue by Yunfeng-Song** [alain-picard/clojure-training#50]
In the class, you gave us an example like this:
```
(go (>! mychan "Hello") (println "We finished putting"))
(go (println "We took" (<! mychan)))
```
And the output was like:

**We finished putting
We took hello**

My question is, in this case, is it certain that "We finished putting" will always get printed before "We took hello"? Is it for sure and why? 

I feel like these two print form gets executed at the same time because the first process is not blocked after getting the value from mychan and the second process is also not blocked.

**Comment by PatrickHo-134** [comment]
I think the second form will wait until a value is put into mychan so the first form will always print first

**Comment by Yunfeng-Song** [comment]
Isn't get and put both got blocked? I mean get will wait for a put while put will wait for a get. I am not sure.

**Comment by PatrickHo-134** [comment]
As I remember from the book, go implements some kind of waiting called "parking". Different from blocking (as when you use future) in which a thread stops execution until a task is complete. Parking frees up the thread so it can keep doing work.

(Not sure if I make it clear for you, but hope it help 😄)

**Comment by Yunfeng-Song** [comment]
Thanks bro. I think I need to read the book again. haha. I still don't fully understand parking.

**Comment by alain-picard** [comment]
Patrick is correct.  The "put" has to finish succeeding before the "take" can begin, so the order of prints you see is to be expected.
