### ISSUE TITLE
onChange handler(when user type something on the input field, it gets trigered)

### ISSUE THREAD

**Issue by Yunfeng-Song** [alain-picard/clojure-training#52]
For example, in the onChange handler function if I want to modify two things of an atom(set a new value and add a new element to a vector), can I write two `swap!` forms inside the onChange handler function or do I need to use transaction?

The atom could be something like: `{:value "" :list ["hehe" "xixi"]}`

**Comment by alain-picard** [comment]
There are no transactions (no refs) in clojurescript (because it has no real threads!) so you can definitely use two swaps.

**Comment by Yunfeng-Song** [comment]
Yeah, that makes sense. No real threads! Thanks.
