### ISSUE TITLE
enter button vs return key

### ISSUE THREAD

**Issue by Yunfeng-Song** [alain-picard/clojure-training#54]
In the requirement, I saw something like this:
> Note that the “Enter” button, and the return key in the text input behave the same way. Keep that in mind in your solution!

Does it mean return key and "Enter" button should call the same dispatch function or should return key triggers a click event on "Enter" button?

Right now I am just calling the same dispatch function.

**Comment by xRayWx** [comment]
Yes, thats what I have to, but each one goes through a different helper function before calling the same dispatch function

**Comment by alain-picard** [comment]
Yes, same dispatch function is what I had in mind, to decouple the "what" from the "how".
