### ISSUE TITLE
Error when importing new libraries to project

### ISSUE THREAD

**Issue by PatrickHo-134** [alain-picard/clojure-training#55]
I tried to import some UI libraries to my project but after loading the project again, only the header of the page is displayed. Have anyone experienced the same issue like this?

This is what got printed in my console 
![error1](https://user-images.githubusercontent.com/54515881/82745932-43d35000-9dcd-11ea-8d4c-ce92cbb82c1e.JPG)

**Comment by alain-picard** [comment]
Property "call" of undefined is often meaning you're trying to call 'nil' as a function?

As if you had code like ((:foo some-map) some-arg) and the first clause returned nil?

Or did you subscribe to an atom instead of a vector?  Remember, it's
(subscribe [:foo args]), not (subscribe :foo)
